CREATE TABLE IF NOT EXISTS `SPARK_JAR` (
  `ID` VARCHAR(40) NOT NULL,
  `CRT_DTTM` DATETIME(0) NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT(1) NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME(0) NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT(20) NULL DEFAULT NULL COMMENT 'Version',
  `JAR_NAME` VARCHAR(1000) COMMENT 'jar name',
  `JAR_URL` VARCHAR(1000) COMMENT 'jar url',
  `MOUNT_ID` VARCHAR(1000) COMMENT 'jar mount id',
  `STATUS` VARCHAR(255) COMMENT 'Spark jar status',
  PRIMARY KEY (ID)) ENGINE=INNODB;