CREATE TABLE IF NOT EXISTS `SPARK_JAR` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT COMMENT 'Version',
  `JAR_NAME` VARCHAR(1000) COMMENT 'jar name',
  `JAR_URL` VARCHAR(1000) COMMENT 'jar url',
  `MOUNT_ID` VARCHAR(1000) COMMENT 'jar mount id',
  `STATUS` VARCHAR(255) COMMENT 'Spark jar status'
);

ALTER TABLE `FLOW` MODIFY COLUMN `DESCRIPTION` TEXT COMMENT 'description';
ALTER TABLE `FLOW_PROCESS` MODIFY COLUMN `DESCRIPTION` TEXT COMMENT 'description';
ALTER TABLE `FLOW_PROCESS_GROUP` MODIFY COLUMN `DESCRIPTION` TEXT COMMENT 'description';
ALTER TABLE `FLOW_PROCESS_STOP` MODIFY COLUMN `DESCRIPTION` TEXT;
ALTER TABLE `FLOW_PROCESS_STOP_PROPERTY` MODIFY COLUMN `CUSTOM_VALUE` TEXT;
ALTER TABLE `FLOW_PROCESS_STOP_PROPERTY` MODIFY COLUMN `DESCRIPTION` TEXT COMMENT 'description';
ALTER TABLE `FLOW_PROCESS_STOP_PROPERTY` MODIFY COLUMN `DISPLAY_NAME` TEXT;
ALTER TABLE `FLOW_PROCESS_STOP_PROPERTY` MODIFY COLUMN `NAME` TEXT;
ALTER TABLE `FLOW_STOPS` MODIFY COLUMN `DESCRIPTION` TEXT;
ALTER TABLE `FLOW_STOPS_PROPERTY` MODIFY COLUMN `ALLOWABLE_VALUES` TEXT;
ALTER TABLE `FLOW_STOPS_PROPERTY` MODIFY COLUMN `CUSTOM_VALUE` TEXT COMMENT 'custom value';
ALTER TABLE `FLOW_STOPS_PROPERTY` MODIFY COLUMN `DESCRIPTION` TEXT COMMENT 'description';
ALTER TABLE `FLOW_STOPS_PROPERTY` MODIFY COLUMN `DISPLAY_NAME` TEXT;
ALTER TABLE `FLOW_STOPS_TEMPLATE` MODIFY COLUMN `DESCRIPTION` TEXT;
ALTER TABLE `FLOW_STOPS_PROPERTY_TEMPLATE` ADD COLUMN `LANGUAGE` VARCHAR(255) NULL COMMENT 'language';
ALTER TABLE `FLOW_STOPS_TEMPLATE` ADD COLUMN `VISUALIZATION_TYPE` VARCHAR(255) NULL COMMENT 'visualization type';

DELETE FROM sys_init_records WHERE id='8a80d89774dd81080174dd890bbb0002';