CREATE TABLE IF NOT EXISTS `TEST_DATA` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT NULL DEFAULT NULL COMMENT 'Version',
  `NAME` VARCHAR(1000) COMMENT 'name',
  `DESCRIPTION` TEXT COMMENT 'description'
);

CREATE TABLE IF NOT EXISTS `TEST_DATA_SCHEMA` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT NULL DEFAULT NULL COMMENT 'Version',
  `FK_TEST_DATA_ID` VARCHAR(40) COMMENT 'fk test_data id',
  `FIELD_NAME` VARCHAR(1000) COMMENT 'field_name',
  `FIELD_TYPE` VARCHAR(1000) COMMENT 'field_type',
  `FIELD_DESCRIPTION` TEXT COMMENT 'description',
  `FIELD_SOFT` BIGINT COMMENT 'soft',
);

CREATE TABLE IF NOT EXISTS `TEST_DATA_SCHEMA_VALUES` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT NULL DEFAULT NULL COMMENT 'Version',
  `FK_TEST_DATA_ID` VARCHAR(40) COMMENT 'fk test_data id',
  `FK_TEST_DATA_SCHEMA_id` VARCHAR(40) COMMENT 'fk test_data_schema id',
  `FIELD_VALUE` VARCHAR(1000) COMMENT 'field type',
  `DATA_ROW` BIGINT COMMENT 'data row'
);
