-- ----------------------------
-- Add column
-- ----------------------------
ALTER TABLE `FLOW_STOPS` ADD COLUMN `IS_DISABLED` BIT(1) NULL AFTER `IS_DATA_SOURCE`;
ALTER TABLE `FLOW_STOPS_TEMPLATE` ADD COLUMN `IMAGE_URL` VARCHAR(255) NULL COMMENT 'stop image url' AFTER `IS_DATA_SOURCE`;