CREATE TABLE IF NOT EXISTS `NOTE_BOOK` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT NULL DEFAULT NULL COMMENT 'Version',
  `NAME` VARCHAR(1000) COMMENT 'name',
  `DESCRIPTION` TEXT COMMENT 'description',
  `SESSIONS_ID` VARCHAR(255) COMMENT '`sessions id',
  `CODE_TYPE` VARCHAR(255) NOT NULL COMMENT 'code type'
);

CREATE TABLE IF NOT EXISTS `CODE_SNIPPET` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT NULL DEFAULT NULL COMMENT 'Version',
  `FK_NOTE_BOOK_ID` VARCHAR(40) COMMENT 'fk node_book id',
  `EXECUTE_ID` VARCHAR(40) COMMENT 'execute code id',
  `CODE_CONTENT` TEXT COMMENT 'code content',
  `CODE_SNIPPET_SORT` BIGINT COMMENT 'soft'
);
ALTER TABLE `CODE_SNIPPET` ADD CONSTRAINT `FK22rp96r4290eons0000000002` FOREIGN KEY (`FK_NOTE_BOOK_ID`) REFERENCES `NOTE_BOOK` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE IF NOT EXISTS `FLOW_GLOBAL_PARAMS` (
  `ID` VARCHAR(40) PRIMARY KEY NOT NULL,
  `CRT_DTTM` DATETIME NOT NULL COMMENT 'Create date time',
  `CRT_USER` VARCHAR(255) NOT NULL COMMENT 'Create user',
  `ENABLE_FLAG` BIT NOT NULL COMMENT 'Enable flag',
  `LAST_UPDATE_DTTM` DATETIME NOT NULL COMMENT 'Last update date time',
  `LAST_UPDATE_USER` VARCHAR(255) NOT NULL COMMENT 'Last update user',
  `VERSION` BIGINT NULL DEFAULT NULL COMMENT 'Version',
  `NAME` VARCHAR(1000) COMMENT 'name',
  `TYPE` VARCHAR(255) COMMENT 'type',
  `CONTENT` TEXT COMMENT 'content'
);

CREATE TABLE IF NOT EXISTS `ASSOCIATION_GLOBAL_PARAMS_FLOW` (
    "GLOBAL_PARAMS_ID" VARCHAR(40) NOT NULL COMMENT 'FLOW_GLOBAL_PARAMS primary key id',
    "FLOW_ID" VARCHAR(40) COMMENT 'FLOW primary key id',
    "PROCESS_ID" VARCHAR(40) COMMENT 'PROCESS primary key id'
);
ALTER TABLE `ASSOCIATION_GLOBAL_PARAMS_FLOW` ADD CONSTRAINT `FK22rp96r4290eons0000000003` FOREIGN KEY (`GLOBAL_PARAMS_ID`) REFERENCES `FLOW_GLOBAL_PARAMS` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `ASSOCIATION_GLOBAL_PARAMS_FLOW` ADD CONSTRAINT `FK22rp96r4290eons0000000004` FOREIGN KEY (`FLOW_ID`) REFERENCES `FLOW` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `ASSOCIATION_GLOBAL_PARAMS_FLOW` ADD CONSTRAINT `FK22rp96r4290eons0000000005` FOREIGN KEY (`PROCESS_ID`) REFERENCES `FLOW_PROCESS` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
